### ISSUE TITLE
local development environment

### ISSUE THREAD

**Issue by hxrts** [AOzone/median#138]
Meeting with @troyth & @provolot the other day, we discussed offloading some of the development outside the core feature set to the community, per your approval @broskoski. The ability to clone down the median app and develop locally would help significantly with this. It looks like most everything is in place but some operating instructions would go a long way if you can find a moment. thx!

**Comment by broskoski** [comment]
Hey @hxrts, updated the README with installation info. Comment on this issue if anything doesn't work as described!

**Comment by hxrts** [comment]
Amazing, thanks cab. I'll pull everything down this weekend and let you know if I run into any issues.

**Comment by hxrts** [comment]
App successfully builds locally on El Capitan, though I needed to install foreman (as ruby gem, not a node package) which we may want include in the README.

Assume you guys are tightening things down before handing out API keys, but wondering if there are plans to publicly expose GET-only access to endpoints needed for local dev. Alternatively, a script for auto-populating the local db could make this a bit more friendly for ppl looking to contribute to the codebase w/o playing the market for a full user key. @troyth may want to weigh in on this pt.

Either way I'd encourage a solution that gives devs a make target to build median locally with at least a pseudo-backend.

Apologies for suggesting additional work but hopefully this will help free you up in the long run.

**Comment by troyth** [comment]
Thanks @broskoski! I just tried to install as well... required this gist to get Mongo running on OS X 10.9: https://gist.github.com/adamgibbons/cc7b263ab3d52924d83b

Otherwise, got it installed, but all urls redirect to the /sorry page. @broskoski any idea what's up?

@hxrts: yes, we will add API docs for some of the kernel. @dochugo will need to determine which we can publish and how to throttle. Perhaps the best move is for the Guggenheim to host a test kernel with it's own IP.

**Comment by troyth** [comment]
@hxrts looks like this is fixed now! @broskoski made some changes, so be sure to `git pull upstream master` and then run the `make assets` command that is now in the `readme.md` before running `npm run dev`. It worked for me, so let me know if it works for you.

**Comment by hxrts** [comment]
Works beautifully. Thanks @broskoski, @troyth. Great that we'll have this ready for the meet up. One last thing, a list of API endpoints would also be quite handy for developers.
