### ISSUE TITLE
A user should be able to see a list of contracts

### ISSUE THREAD

**Issue by broskoski** [AOzone/median#4]

**Comment by troyth** [comment]
Here's the initial sketches from @aarongillett. The idea is to blend something that will be clear and familiar enough to ppl used to using stock market apps, yet not intimidating to non-superusers. The idea shown here is a layering of a list and the stock charts, which would be isolated on hover/tap.
![150828_futureslists_page_5](https://cloud.githubusercontent.com/assets/2113599/9564597/46c3e83a-4e7a-11e5-869f-d8719c934584.png)
![150828_futureslists_page_6](https://cloud.githubusercontent.com/assets/2113599/9564598/46ca3c1c-4e7a-11e5-93c6-50f42c92eed7.png)
![150828_futureslists_page_7](https://cloud.githubusercontent.com/assets/2113599/9564599/46cd10d6-4e7a-11e5-84aa-8e78a863b285.png)
