### ISSUE TITLE
blog call-sign links broken

### ISSUE THREAD

**Issue by hxrts** [AOzone/median#88]
clicking yields "Internal Error, Cannot read property 'then' of undefined"

**Comment by broskoski** [comment]
Can't replicate, from which page and to what url? Thanks!

**Comment by mariofaranda** [comment]
This is because those futures linked on the blog page are not in the futures list anymore

**Comment by broskoski** [comment]
Ah, yes. Dummy data. @troyth needs to update the blog using real futures.
